language: ruby
cache: bundler

env:
  global:
    - LOCAL_DOMAIN=example.com
    - LOCAL_HTTPS=false

addons:
  postgresql: 9.4

rvm:
  - 2.2.4

services:
  - redis-server

bundler_args: --without development --retry=3 --jobs=3

before_script:
  - bundle exec rake db:create db:migrate

script: bundle exec rspec
