language: ruby
cache: bundler

env:
  global:
    - LOCAL_DOMAIN=cb6e6126.ngrok.io
    - LOCAL_HTTPS=true
    - RAILS_ENV=test

addons:
  postgresql: 9.4

rvm:
  - 2.2.4

services:
  - redis-server

bundler_args: --without development production --retry=3 --jobs=3

install:
  - npm install -g npm@2
  - npm install
  - bundle install

before_script:
  - bundle exec rails db:create db:migrate

script: bundle exec rspec
