language: ruby
cache: bundler

env:
  global:
    - LOCAL_DOMAIN=cb6e6126.ngrok.io
    - LOCAL_HTTPS=true
    - RAILS_ENV=test

addons:
  postgresql: 9.4

rvm:
  - 2.2.4

services:
  - redis-server

bundler_args: --without development production --retry=3 --jobs=3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y nodejs nodejs-legacy npm

before_script:
  - npm install
  - bundle exec rake db:create db:migrate

script: bundle exec rspec
